# Lowzin Linux Example Config
#
# This file shows some of the customizable settings that Lowzin will support.

overlays=gentoo,archlinux,alpine
cybertools=yes
default_shell=/bin/zsh
hyprland=yes
custom_startup_script=/etc/lowzin/startup.sh
